### ISSUE TITLE
Make the project more generally

### ISSUE THREAD

**Issue by mboussaid** [mynaparrot/plugNmeet-recorder#109]
Hello i'm really interested on this project i'm already trying to build a similar project [xfp-streamer](https://github.com/mboussaid/xfp-streamer) 
i hope if we could contribute together to build an open source project 
the idea is for example we can record a given video url or stream it to rtmp i mean make it more generally and flexible so anyone can use it as he want
i really did a lot of research for that and i didn't find anything helpful
please contact me if you are interested

**Comment by jibon57** [comment]
You are free to use any code from this project under repo license term. Good luck
