### ISSUE TITLE
can this recorder record multiple room at same time?

### ISSUE THREAD

**Issue by gigabyteservice** [mynaparrot/plugNmeet-recorder#42]
can this recorder record multiple rooms at the same time? if yes then e.g how many CPUs and RAM need for recording 3 sessions at the same time? (let supposed we want to use AWS server)  if not then how to do scaling for recording multiple sessions at the same time?

**Comment by jibon57** [comment]
Yes, multiple sessions can be recorded concurrently. This is CPU intensive program. Need ~2 cores for each session.
